apiVersion: v1
kind: Secret
metadata:
  name: carelink-atlas
  namespace: carelink
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://txngjr:PRzEAXyKMnqwxfY8@cluster0.tha54x2.mongodb.net/carelink?retryWrites=true&w=majority"
