apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carelink
resources:
  - namespace.yaml
  - secret.yaml
  - mongo.yaml
  - backend.yaml
  - web.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: carelink
images:
  - name: carelink-backend
    newName: ghcr.io/txngjr/carelink-argocd-backend
    newTag: sha-f3acfe3
  - name: carelink-web
    newName: ghcr.io/txngjr/carelink-argocd-web
    newTag: sha-f3acfe3

