apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carelink
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongo.yaml
  - app.yaml
  - operations.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: carelink
images:
  - name: carelink-app
    newName: ghcr.io/txngjr/carelink-argocd-web
    newTag: sha-a142135
